// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef BEMAN_MONADICS_DETAIL_CONFIG_HPP
#define BEMAN_MONADICS_DETAIL_CONFIG_HPP

#ifdef BEMAN_MONADICS_MODULE_INTERFACE
#define BEMAN_MONADICS_MODULE_BEGIN_EXPORT export {
#define BEMAN_MONADICS_MODULE_END_EXPORT }
#define BEMAN_MONADICS_MODULE_EXPORT export
#else
#define BEMAN_MONADICS_MODULE_BEGIN_EXPORT
#define BEMAN_MONADICS_MODULE_END_EXPORT
#define BEMAN_MONADICS_MODULE_EXPORT
#endif

#endif // BEMAN_MONADICS_DETAIL_CONFIG_HPP
